/**
 * DataSF g8m3-pdis：企业经 SF 税务登记，但 `city` 常为湾区实地城市。
 * 用 `state = 'CA'` + `upper(trim(city)) in (...)` 限定九县及周边常见市名，减少脏数据（邮编当城市、海外地址等）。
 *
 * 列表为 SoQL `in` 用大写，与 `upper(trim(city))` 对齐；含常见变体（如 ST HELENA / ST. HELENA）。
 */
export const BAY_AREA_CITIES_UPPER_FOR_DATA_SF: readonly string[] = [
  'ALAMEDA',
  'ALBANY',
  'AMERICAN CANYON',
  'ANTIOCH',
  'ASHLAND',
  'ATHERTON',
  'BELMONT',
  'BELVEDERE',
  'BENICIA',
  'BERKELEY',
  'BETHEL ISLAND',
  'BLACKHAWK',
  'BRENTWOOD',
  'BRISBANE',
  'BURLINGAME',
  'CALISTOGA',
  'CAMPBELL',
  'CASTRO VALLEY',
  'CLAYTON',
  'CLOVERDALE',
  'COLMA',
  'CONCORD',
  'CORTE MADERA',
  'COTATI',
  'CUPERTINO',
  'DALY CITY',
  'DANVILLE',
  'DISCOVERY BAY',
  'DIXON',
  'DUBLIN',
  'EAST PALO ALTO',
  'EL CERRITO',
  'EL SOBRANTE',
  'EMERYVILLE',
  'FAIRFIELD',
  'FAIRVIEW',
  'FOSTER CITY',
  'FREMONT',
  'GILROY',
  'HALF MOON BAY',
  'HAYWARD',
  'HEALDSBURG',
  'HERCULES',
  'HILLSBOROUGH',
  'LAFAYETTE',
  'LARKSPUR',
  'LIVERMORE',
  'LOS ALTOS',
  'LOS ALTOS HILLS',
  'LOS GATOS',
  'MARTINEZ',
  'MENLO PARK',
  'MILL VALLEY',
  'MILLBRAE',
  'MILPITAS',
  'MONTE SERENO',
  'MORAGA',
  'MORGAN HILL',
  'MOUNTAIN VIEW',
  'NAPA',
  'NEWARK',
  'NOVATO',
  'OAKLAND',
  'OAKLEY',
  'ORINDA',
  'PACIFICA',
  'PALO ALTO',
  'PETALUMA',
  'PIEDMONT',
  'PINOLE',
  'PITTSBURG',
  'PLEASANT HILL',
  'PLEASANTON',
  'PORTOLA VALLEY',
  'REDWOOD CITY',
  'RICHMOND',
  'RIO VISTA',
  'RODEO',
  'ROHNERT PARK',
  'ROSS',
  'SAN ANSELMO',
  'SAN BRUNO',
  'SAN CARLOS',
  'SAN FRANCISCO',
  'SAN GREGORIO',
  'SAN JOSE',
  'SAN LEANDRO',
  'SAN LORENZO',
  'SAN MATEO',
  'SAN PABLO',
  'SAN RAFAEL',
  'SAN RAMON',
  'SANTA CLARA',
  'SANTA ROSA',
  'SARATOGA',
  'SAUSALITO',
  'SEBASTOPOL',
  'SONOMA',
  'SOUTH SAN FRANCISCO',
  'ST HELENA',
  'ST. HELENA',
  'STINSON BEACH',
  'SUISUN CITY',
  'SUNNYVALE',
  'SUNOL',
  'TIBURON',
  'TRACY',
  'UNION CITY',
  'VACAVILLE',
  'VALLEJO',
  'WALNUT CREEK',
  'WINDSOR',
  'WOODSIDE',
  'YOUNTVILLE',
].sort((a, b) => a.localeCompare(b));

export function escapeSoqlStringLiteral(s: string): string {
  return s.replace(/'/g, "''");
}

/** SoQL：`upper(trim(city)) in ('A','B',...)` 内层列表（不含括号） */
export function buildBayAreaCityUpperInListSoql(): string {
  return BAY_AREA_CITIES_UPPER_FOR_DATA_SF.map(
    (c) => `'${escapeSoqlStringLiteral(c)}'`,
  ).join(', ');
}
